apiVersion: apps/v1
kind: Deployment
metadata:
  name: behave-deployment
  labels:
    app: behave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: behave
  template:
    metadata:
      labels:
        app: behave
    spec:
      containers:
        - name: behave-service
          image: behave-service-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30020
          env:
            - name: ENV
              value: "local"
            - name: ENTRY_POINT
              value: "k8s"
            - name: PORT
              value: "30020"
            - name: DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: mongo-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PASSWORD
            - name: EVENT_BUS_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: event-bus-url
            - name: EVENT_BUS_PORT
              value: "30000"
---
apiVersion: v1
kind: Service
metadata:
  name: behave-service
spec:
  type: NodePort
  selector:
    app: behave
  ports:
    - protocol: TCP
      port: 30020
      targetPort: 30020
      nodePort: 30020
